import {
  AlertTriangle,
  Archive,
  ArrowDownAZ,
  ArrowLeftRight,
  ArrowLeftSquare,
  ArrowRightCircle,
  ArrowRightSquare,
  ArrowUpDown,
  BarChart3,
  Bell,
  Bookmark,
  BookmarkCheck,
  BookOpen,
  Bot,
  Boxes,
  Briefcase,
  Building2,
  Bug,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clock,
  CloudUpload,
  Columns,
  Cpu,
  Diamond,
  Download,
  FileDigit,
  FileDown,
  FileText,
  FileUp,
  Flag,
  Folder,
  FolderCheck,
  FolderOpen,
  FolderPlus,
  Gauge,
  Globe,
  GraduationCap,
  GanttChart,
  Hash,
  HardDrive,
  History,
  Home,
  Hourglass,
  IdCard,
  Inbox,
  KeyRound,
  Languages,
  LayoutGrid,
  LayoutTemplate,
  Library,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  Mail,
  Menu,
  MessageCircle,
  MessageSquare,
  Milestone,
  MessagesSquare,
  Network,
  Newspaper,
  Package,
  Paperclip,
  Palette,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  RefreshCw,
  Reply,
  Rocket,
  RotateCcw,
  Save,
  ScanLine,
  Search,
  Send,
  Settings,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tags,
  Target,
  Trash2,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  UserPlus,
  Users,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Registre central des icônes — équivalents lucide-react des `bi-*` (Bootstrap
 * Icons) utilisées par le menu Blade réel (`resources/views/layouts/app.blade.php`
 * et `resources/views/submenu/*.blade.php`). Les composants ne référencent
 * jamais `lucide-react` directement : ils passent par une clé résolue ici.
 */
export const icons = {
  // Menus racine (rail)
  mails: Mail,
  workflow: Network,
  workplaces: Briefcase,
  briefcase: Briefcase,
  building2: Building2,
  chats: MessageSquare,
  records: Folder,
  communications: MessagesSquare,
  transferrings: ArrowLeftRight,
  deposits: Building2,
  tools: Wrench,
  dollies: ShoppingCart,
  contacts: Users,
  public: Globe,
  aiSearch: Bot,
  settings: Settings,
  projects: Rocket,
  target: Target,

  // Génériques (sous-menus)
  dashboard: LayoutGrid,
  listCheck: ListChecks,
  archive: Archive,
  trash: Trash2,
  person: User,
  personPlus: UserPlus,
  personCheck: UserCheck,
  personBadge: IdCard,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  calendarDays: CalendarDays,
  key: KeyRound,
  history: History,
  clock: Clock,
  hourglass: Hourglass,
  search: Search,
  plusSquare: PlusSquare,
  plusCircle: PlusCircle,
  plus: Plus,
  cloudUpload: CloudUpload,
  arrowUpDown: ArrowUpDown,
  inbox: Inbox,
  send: Send,
  tags: Tags,
  bookmark: Bookmark,
  bookmarkCheck: BookmarkCheck,
  arrowRightSquare: ArrowRightSquare,
  arrowLeftSquare: ArrowLeftSquare,
  playCircle: PlayCircle,
  gauge: Gauge,
  listTodo: ListTodo,
  list: List,
  refresh: RefreshCw,
  checkCircle: CheckCircle2,
  home: Home,
  book: BookOpen,
  network: Network,
  listOrdered: ListOrdered,
  sliders: SlidersHorizontal,
  library: Library,
  folderOpen: FolderOpen,
  folderPlus: FolderPlus,
  folderCheck: FolderCheck,
  fileText: FileText,
  fileUp: FileUp,
  fileDown: FileDown,
  fileDigit: FileDigit,
  flag: Flag,
  hardDrive: HardDrive,
  sortAlpha: ArrowDownAZ,
  scan: ScanLine,
  arrowRightCircle: ArrowRightCircle,
  cart: ShoppingCart,
  rotateCcw: RotateCcw,
  download: Download,
  upload: Upload,
  package: Package,
  shieldLock: ShieldCheck,
  alertTriangle: AlertTriangle,
  trendingUp: TrendingUp,
  barChart: BarChart3,
  palette: Palette,
  newspaper: Newspaper,
  layoutTemplate: LayoutTemplate,
  reply: Reply,
  paperclip: Paperclip,
  messageCircle: MessageCircle,
  star: Star,
  sparkles: Sparkles,
  zap: Zap,
  hash: Hash,
  bug: Bug,
  cpu: Cpu,
  save: Save,
  languages: Languages,
  settings2: Settings2,
  diamond: Diamond,
  graduationCap: GraduationCap,
  bell: Bell,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  columns: Columns,
  gantt: GanttChart,
  milestone: Milestone,
  users: Users,
  globe: Globe,
  menu: Menu,
  close: X,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof icons;

export function Icon({ name, className }: { name: IconKey; className?: string }) {
  const Cmp = icons[name];
  return <Cmp className={className} aria-hidden="true" />;
}
