<?php

namespace Database\Seeders\Tools;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ThesaurusTypologieSeeder extends Seeder
{
    public function run()
    {
        // VÃ©rifier si le schÃ©ma existe dÃ©jÃ 
        $existingScheme = DB::table('thesaurus_schemes')
            ->where('uri', 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3')
            ->first();

        if ($existingScheme) {
            $this->command->info('Le thÃ©saurus des typologies documentaires existe dÃ©jÃ .');
            $schemeId = $existingScheme->id;
        } else {
            // CrÃ©er le schÃ©ma de thÃ©saurus pour la typologie
            $schemeId = DB::table('thesaurus_schemes')->insertGetId([
                'uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3',
                'identifier' => 'T3',
                'title' => 'ThÃ©saurus des typologies documentaires',
                'description' => 'ThÃ©saurus normalisÃ© des types de documents',
                'language' => 'fr-fr',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $this->command->info('SchÃ©ma du thÃ©saurus des typologies documentaires crÃ©Ã©.');
        }

        // Tableau des concepts Ã  insÃ©rer
        $concepts = [
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-34', 'notation' => 'TYP34', 'label' => 'bulle pontificale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-53', 'notation' => 'TYP53', 'label' => 'catalogue'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-198', 'notation' => 'TYP198', 'label' => 'registre du courrier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-83', 'notation' => 'TYP83', 'label' => 'dÃ©claration d\'intention d\'aliÃ©ner'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-157', 'notation' => 'TYP157', 'label' => 'permis de recherche'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-56', 'notation' => 'TYP56', 'label' => 'chanson'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-118', 'notation' => 'TYP118', 'label' => 'livre comptable', 'alt_label' => 'grand livre'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-185', 'notation' => 'TYP185', 'label' => 'rapport d\'activitÃ©', 'alt_label' => 'bilan d\'activitÃ©'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-203', 'notation' => 'TYP203', 'label' => 'rÃ¨glement d\'entreprise'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-32', 'notation' => 'TYP32', 'label' => 'budget primitif'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-199', 'notation' => 'TYP199', 'label' => 'registre matricule'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-196', 'notation' => 'TYP196', 'label' => 'registre des entrÃ©es et des sorties'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-76', 'notation' => 'TYP76', 'label' => 'dÃ©cision budgÃ©taire modificative'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-18', 'notation' => 'TYP18', 'label' => 'atlas'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-217', 'notation' => 'TYP217', 'label' => 'schÃ©ma directeur d\'amÃ©nagement et d\'urbanisme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-81', 'notation' => 'TYP81', 'label' => 'dÃ©claration de succession'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-8', 'notation' => 'TYP8', 'label' => 'agenda'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-77', 'notation' => 'TYP77', 'label' => 'dÃ©cision de paiement'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-64', 'notation' => 'TYP64', 'label' => 'compte d\'exploitation'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-99', 'notation' => 'TYP99', 'label' => 'dossier des ouvrages exÃ©cutÃ©s'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-4', 'notation' => 'TYP4', 'label' => 'acte de congrÃ¨s'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-116', 'notation' => 'TYP116', 'label' => 'liste Ã©lectorale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-74', 'notation' => 'TYP74', 'label' => 'coupure de presse'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-26', 'notation' => 'TYP26', 'label' => 'bilan comptable'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-96', 'notation' => 'TYP96', 'label' => 'dossier de pension'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-197', 'notation' => 'TYP197', 'label' => 'registre du commerce et des sociÃ©tÃ©s'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-94', 'notation' => 'TYP94', 'label' => 'dossier de carriÃ¨re'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-168', 'notation' => 'TYP168', 'label' => 'portrait'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-180', 'notation' => 'TYP180', 'label' => 'protÃªt'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-146', 'notation' => 'TYP146', 'label' => 'notice individuelle'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-23', 'notation' => 'TYP23', 'label' => 'bail'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-13', 'notation' => 'TYP13', 'label' => 'arrÃªtÃ© d\'alignement'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-125', 'notation' => 'TYP125', 'label' => 'main courante'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-158', 'notation' => 'TYP158', 'label' => 'pÃ©tition', 'alt_label' => 'placet'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-112', 'notation' => 'TYP112', 'label' => 'inventaire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-214', 'notation' => 'TYP214', 'label' => 'rÃ´le d\'imposition'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-151', 'notation' => 'TYP151', 'label' => 'panneau d\'exposition'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-183', 'notation' => 'TYP183', 'label' => 'questionnaire d\'enquÃªte', 'alt_label' => 'feuille de mÃ©nage'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-159', 'notation' => 'TYP159', 'label' => 'document photographique', 'alt_label' => 'diapositive'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-60', 'notation' => 'TYP60', 'label' => 'circulaire', 'alt_label' => 'instruction'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-33', 'notation' => 'TYP33', 'label' => 'budget supplÃ©mentaire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-115', 'notation' => 'TYP115', 'label' => 'liste d\'Ã©margement'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-202', 'notation' => 'TYP202', 'label' => 'rÃ¨glement'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-204', 'notation' => 'TYP204', 'label' => 'rÃ¨glement intÃ©rieur'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-57', 'notation' => 'TYP57', 'label' => 'charte'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-156', 'notation' => 'TYP156', 'label' => 'permis de dÃ©molir'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-84', 'notation' => 'TYP84', 'label' => 'dÃ©claration d\'utilitÃ© publique'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-3', 'notation' => 'TYP3', 'label' => 'acte civil public'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-89', 'notation' => 'TYP89', 'label' => 'document audiovisuel', 'alt_label' => 'film'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-19', 'notation' => 'TYP19', 'label' => 'atlas terrier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-111', 'notation' => 'TYP111', 'label' => 'inscription hypothÃ©caire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-25', 'notation' => 'TYP25', 'label' => 'bibliographie'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-122', 'notation' => 'TYP122', 'label' => 'livre liturgique', 'alt_label' => 'missel'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-127', 'notation' => 'TYP127', 'label' => 'manifeste de navire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-52', 'notation' => 'TYP52', 'label' => 'cartulaire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-132', 'notation' => 'TYP132', 'label' => 'matrice d\'imposition'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-216', 'notation' => 'TYP216', 'label' => 'schÃ©ma directeur'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-105', 'notation' => 'TYP105', 'label' => 'Ã©tude'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-16', 'notation' => 'TYP16', 'label' => 'arrÃªtÃ© du prÃ©sident du conseil rÃ©gional'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-27', 'notation' => 'TYP27', 'label' => 'bilan pÃ©dagogique'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-176', 'notation' => 'TYP176', 'label' => 'procÃ¨s-verbal d\'examen'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-206', 'notation' => 'TYP206', 'label' => 'rÃ©pertoire civil'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-135', 'notation' => 'TYP135', 'label' => 'menu'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-9', 'notation' => 'TYP9', 'label' => 'album'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-179', 'notation' => 'TYP179', 'label' => 'programme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-192', 'notation' => 'TYP192', 'label' => 'registre d\'appel'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-212', 'notation' => 'TYP212', 'label' => 'rÃ´le'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-129', 'notation' => 'TYP129', 'label' => 'marchÃ© public'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-231', 'notation' => 'TYP231', 'label' => 'tract'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-59', 'notation' => 'TYP59', 'label' => 'chrono', 'alt_label' => 'minutier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-17', 'notation' => 'TYP17', 'label' => 'arrÃªtÃ© prÃ©fectoral'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-162', 'notation' => 'TYP162', 'label' => 'plan cadastral'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-208', 'notation' => 'TYP208', 'label' => 'rÃ©pertoire des opÃ©rations de douanes'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-148', 'notation' => 'TYP148', 'label' => 'ordre de mission'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-126', 'notation' => 'TYP126', 'label' => 'manifeste d\'aÃ©ronef'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-140', 'notation' => 'TYP140', 'label' => 'modÃ¨le de fabrique'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-67', 'notation' => 'TYP67', 'label' => 'contrat'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-61', 'notation' => 'TYP61', 'label' => 'communiquÃ© de presse'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-170', 'notation' => 'TYP170', 'label' => 'procÃ¨s-verbal'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-209', 'notation' => 'TYP209', 'label' => 'rÃ©pertoire d\'officier public ministÃ©riel'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-1', 'notation' => 'TYP1', 'label' => 'accord de travail'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-103', 'notation' => 'TYP103', 'label' => 'Ã©tat du montant des rÃ´les'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-131', 'notation' => 'TYP131', 'label' => 'matrice cadastrale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-45', 'notation' => 'TYP45', 'label' => 'carte de membre'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-145', 'notation' => 'TYP145', 'label' => 'note de service'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-22', 'notation' => 'TYP22', 'label' => 'avis'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-136', 'notation' => 'TYP136', 'label' => 'mercuriale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-29', 'notation' => 'TYP29', 'label' => 'brevet d\'invention'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-55', 'notation' => 'TYP55', 'label' => 'certificat d\'urbanisme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-2', 'notation' => 'TYP2', 'label' => 'acte authentique', 'alt_label' => 'testament'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-137', 'notation' => 'TYP137', 'label' => 'microforme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-147', 'notation' => 'TYP147', 'label' => 'objet'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-7', 'notation' => 'TYP7', 'label' => 'affiche', 'alt_label' => 'placard'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-167', 'notation' => 'TYP167', 'label' => 'poÃ¨me'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-14', 'notation' => 'TYP14', 'label' => 'arrÃªtÃ© du maire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-21', 'notation' => 'TYP21', 'label' => 'avant-projet', 'alt_label' => 'avant-projet dÃ©finitif'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-207', 'notation' => 'TYP207', 'label' => 'rÃ©pertoire des mÃ©tiers'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-71', 'notation' => 'TYP71', 'label' => 'convention de formation'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-154', 'notation' => 'TYP154', 'label' => 'permis', 'alt_label' => 'licence'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-58', 'notation' => 'TYP58', 'label' => 'chronique'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-194', 'notation' => 'TYP194', 'label' => 'registre de catholicitÃ©'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-130', 'notation' => 'TYP130', 'label' => 'marque de fabrique'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-43', 'notation' => 'TYP43', 'label' => 'carte Ã  jouer'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-164', 'notation' => 'TYP164', 'label' => 'plan de secours'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-153', 'notation' => 'TYP153', 'label' => 'passeport'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-30', 'notation' => 'TYP30', 'label' => 'brochure'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-232', 'notation' => 'TYP232', 'label' => 'transcription hypothÃ©caire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-205', 'notation' => 'TYP205', 'label' => 'rÃ©pertoire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-233', 'notation' => 'TYP233', 'label' => 'warrant'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-5', 'notation' => 'TYP5', 'label' => 'acte de sociÃ©tÃ©'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-128', 'notation' => 'TYP128', 'label' => 'maquette'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-191', 'notation' => 'TYP191', 'label' => 'registre'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-142', 'notation' => 'TYP142', 'label' => 'nomenclature'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-174', 'notation' => 'TYP174', 'label' => 'procÃ¨s-verbal de rÃ©union'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-38', 'notation' => 'TYP38', 'label' => 'cahier des charges'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-139', 'notation' => 'TYP139', 'label' => 'minute notariale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-222', 'notation' => 'TYP222', 'label' => 'sujet d\'examen'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-20', 'notation' => 'TYP20', 'label' => 'autorisation d\'urbanisme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-113', 'notation' => 'TYP113', 'label' => 'laissez-passer'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-41', 'notation' => 'TYP41', 'label' => 'carnet de santÃ©'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-227', 'notation' => 'TYP227', 'label' => 'timbre'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-39', 'notation' => 'TYP39', 'label' => 'calendrier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-28', 'notation' => 'TYP28', 'label' => 'bilan social'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-182', 'notation' => 'TYP182', 'label' => 'publication pÃ©riodique'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-161', 'notation' => 'TYP161', 'label' => 'plan'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-62', 'notation' => 'TYP62', 'label' => 'compte administratif'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-186', 'notation' => 'TYP186', 'label' => 'rapport de gendarmerie'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-63', 'notation' => 'TYP63', 'label' => 'compte de gestion'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-141', 'notation' => 'TYP141', 'label' => 'motion', 'alt_label' => 'voeu'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-143', 'notation' => 'TYP143', 'label' => 'norme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-171', 'notation' => 'TYP171', 'label' => 'procÃ¨s-verbal d\'amÃ©nagement forestier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-225', 'notation' => 'TYP225', 'label' => 'tÃ©lÃ©gramme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-69', 'notation' => 'TYP69', 'label' => 'convention'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-121', 'notation' => 'TYP121', 'label' => 'livre foncier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-48', 'notation' => 'TYP48', 'label' => 'carte d\'identitÃ©'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-165', 'notation' => 'TYP165', 'label' => 'plan d\'occupation des sols'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-85', 'notation' => 'TYP85', 'label' => 'dÃ©claration fiscale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-124', 'notation' => 'TYP124', 'label' => 'livret ouvrier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-72', 'notation' => 'TYP72', 'label' => 'copie d\'examen'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-50', 'notation' => 'TYP50', 'label' => 'carte postale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-108', 'notation' => 'TYP108', 'label' => 'fichier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-102', 'notation' => 'TYP102', 'label' => 'Ã©tat de section'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-134', 'notation' => 'TYP134', 'label' => 'mÃ©moire', 'alt_label' => 'thÃ¨se'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-169', 'notation' => 'TYP169', 'label' => 'presse institutionnelle', 'alt_label' => 'bulletin cantonal'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-230', 'notation' => 'TYP230', 'label' => 'titre de sÃ©jour', 'alt_label' => 'carte de sÃ©jour'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-178', 'notation' => 'TYP178', 'label' => 'profession de foi'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-44', 'notation' => 'TYP44', 'label' => 'carte d\'Ã©lecteur'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-226', 'notation' => 'TYP226', 'label' => 'texte officiel', 'alt_label' => 'ordonnance'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-35', 'notation' => 'TYP35', 'label' => 'bulletin de salaire', 'alt_label' => 'bulletin de paie'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-114', 'notation' => 'TYP114', 'label' => 'liste'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-73', 'notation' => 'TYP73', 'label' => 'correspondance'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-47', 'notation' => 'TYP47', 'label' => 'carte de voeu'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-155', 'notation' => 'TYP155', 'label' => 'permis de construire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-166', 'notation' => 'TYP166', 'label' => 'plan d\'urbanisme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-10', 'notation' => 'TYP10', 'label' => 'annonce officielle et lÃ©gale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-218', 'notation' => 'TYP218', 'label' => 'sommier des marchandises'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-54', 'notation' => 'TYP54', 'label' => 'certificat'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-88', 'notation' => 'TYP88', 'label' => 'discours', 'alt_label' => 'allocution'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-210', 'notation' => 'TYP210', 'label' => 'rÃ©pertoire gÃ©nÃ©ral des affaires civiles'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-97', 'notation' => 'TYP97', 'label' => 'dossier de presse'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-15', 'notation' => 'TYP15', 'label' => 'arrÃªtÃ© du prÃ©sident du conseil gÃ©nÃ©ral'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-149', 'notation' => 'TYP149', 'label' => 'organigramme'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-181', 'notation' => 'TYP181', 'label' => 'publication officielle'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-229', 'notation' => 'TYP229', 'label' => 'titre de propriÃ©tÃ©'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-80', 'notation' => 'TYP80', 'label' => 'dÃ©claration de revenus'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-91', 'notation' => 'TYP91', 'label' => 'document graphique', 'alt_label' => 'estampe'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-120', 'notation' => 'TYP120', 'label' => 'livre d\'or'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-184', 'notation' => 'TYP184', 'label' => 'rapport'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-107', 'notation' => 'TYP107', 'label' => 'faire-part'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-119', 'notation' => 'TYP119', 'label' => 'livre de raison'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-223', 'notation' => 'TYP223', 'label' => 'table'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-100', 'notation' => 'TYP100', 'label' => 'dossier individuel'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-6', 'notation' => 'TYP6', 'label' => 'acte sous seing privÃ©'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-104', 'notation' => 'TYP104', 'label' => 'Ã©tat parcellaire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-219', 'notation' => 'TYP219', 'label' => 'statistique', 'alt_label' => 'Ã©tat'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-42', 'notation' => 'TYP42', 'label' => 'carte'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-31', 'notation' => 'TYP31', 'label' => 'budget'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-150', 'notation' => 'TYP150', 'label' => 'ouvrage imprimÃ©'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-172', 'notation' => 'TYP172', 'label' => 'procÃ¨s-verbal d\'Ã©lection'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-187', 'notation' => 'TYP187', 'label' => 'rapport de mer'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-98', 'notation' => 'TYP98', 'label' => 'dossier de procÃ©dure'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-79', 'notation' => 'TYP79', 'label' => 'dÃ©claration de douane'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-82', 'notation' => 'TYP82', 'label' => 'dÃ©claration de travaux'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-193', 'notation' => 'TYP193', 'label' => 'registre d\'audience', 'alt_label' => 'plumitif d\'audience'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-92', 'notation' => 'TYP92', 'label' => 'documentation'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-109', 'notation' => 'TYP109', 'label' => 'fichier immobilier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-70', 'notation' => 'TYP70', 'label' => 'convention collective'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-160', 'notation' => 'TYP160', 'label' => 'piÃ¨ce comptable', 'alt_label' => 'quittance'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-220', 'notation' => 'TYP220', 'label' => 'statut'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-138', 'notation' => 'TYP138', 'label' => 'minute juridictionnelle', 'alt_label' => 'sentence'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-200', 'notation' => 'TYP200', 'label' => 'registre paroissial'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-163', 'notation' => 'TYP163', 'label' => 'plan d\'alignement'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-86', 'notation' => 'TYP86', 'label' => 'dÃ©libÃ©ration'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-190', 'notation' => 'TYP190', 'label' => 'rapport d\'expertise'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-40', 'notation' => 'TYP40', 'label' => 'caricature'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-65', 'notation' => 'TYP65', 'label' => 'compte financier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-175', 'notation' => 'TYP175', 'label' => 'procÃ¨s-verbal de scellÃ©s'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-201', 'notation' => 'TYP201', 'label' => 'registre protestant'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-188', 'notation' => 'TYP188', 'label' => 'rapport de police'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-144', 'notation' => 'TYP144', 'label' => 'note'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-11', 'notation' => 'TYP11', 'label' => 'annuaire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-68', 'notation' => 'TYP68', 'label' => 'contrat d\'apprentissage'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-24', 'notation' => 'TYP24', 'label' => 'base de donnÃ©es'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-123', 'notation' => 'TYP123', 'label' => 'livret militaire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-173', 'notation' => 'TYP173', 'label' => 'procÃ¨s-verbal d\'enquÃªte'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-78', 'notation' => 'TYP78', 'label' => 'dÃ©claration'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-95', 'notation' => 'TYP95', 'label' => 'dossier de consultation des entreprises'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-195', 'notation' => 'TYP195', 'label' => 'registre d\'Ã©crou'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-87', 'notation' => 'TYP87', 'label' => 'diplÃ´me'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-46', 'notation' => 'TYP46', 'label' => 'carte de travail'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-215', 'notation' => 'TYP215', 'label' => 'sceau'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-213', 'notation' => 'TYP213', 'label' => 'rÃ´le d\'Ã©quipage'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-228', 'notation' => 'TYP228', 'label' => 'titre de circulation'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-12', 'notation' => 'TYP12', 'label' => 'armorial'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-224', 'notation' => 'TYP224', 'label' => 'tarif'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-93', 'notation' => 'TYP93', 'label' => 'dossier de candidature'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-36', 'notation' => 'TYP36', 'label' => 'bulletin de vote'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-177', 'notation' => 'TYP177', 'label' => 'procÃ¨s-verbal d\'infraction'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-133', 'notation' => 'TYP133', 'label' => 'mÃ©daille'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-101', 'notation' => 'TYP101', 'label' => 'dossier mÃ©dical'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-110', 'notation' => 'TYP110', 'label' => 'hypothÃ¨que maritime'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-189', 'notation' => 'TYP189', 'label' => 'rapport de stage'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-211', 'notation' => 'TYP211', 'label' => 'revue de presse'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-66', 'notation' => 'TYP66', 'label' => 'compte rendu'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-90', 'notation' => 'TYP90', 'label' => 'document de sÃ©ance'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-37', 'notation' => 'TYP37', 'label' => 'cahier de dolÃ©ances'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-221', 'notation' => 'TYP221', 'label' => 'statut d\'association'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-51', 'notation' => 'TYP51', 'label' => 'carton d\'invitation'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-49', 'notation' => 'TYP49', 'label' => 'carte d\'identitÃ© professionnelle'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-152', 'notation' => 'TYP152', 'label' => 'partition musicale'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-106', 'notation' => 'TYP106', 'label' => 'exploit d\'huissier'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-117', 'notation' => 'TYP117', 'label' => 'liste nominative'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-235', 'notation' => 'TYP235', 'label' => 'dÃ©cision'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-236', 'notation' => 'TYP236', 'label' => 'dÃ©claration fÃ©odale', 'alt_label' => 'foi et hommage'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-237', 'notation' => 'TYP237', 'label' => 'Ã©crit du for privÃ©', 'alt_label' => 'journal intime'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-238', 'notation' => 'TYP238', 'label' => 'curriculum vitae'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-239', 'notation' => 'TYP239', 'label' => 'dictionnaire'],
            ['uri' => 'http://data.culture.fr/thesaurus/resource/ark:/67717/T3-240', 'notation' => 'TYP240', 'label' => 'nÃ©crologie'],
        ];

        // InsÃ©rer les concepts
        foreach ($concepts as $conceptData) {
            // InsÃ©rer le concept si absent (clÃ©: uri)
            DB::table('thesaurus_concepts')->insertOrIgnore([
                'scheme_id' => $schemeId,
                'uri' => $conceptData['uri'],
                'notation' => $conceptData['notation'],
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // RÃ©cupÃ©rer l'ID du concept
            $concept = DB::table('thesaurus_concepts')->where('uri', $conceptData['uri'])->first();
            if (!$concept) {
                // Fallback improbable si insertOrIgnore a ignorÃ© et non prÃ©sent (concurrence)
                continue;
            }
            $conceptId = $concept->id;

            // Ajouter le label prÃ©fÃ©rÃ© (idempotent)
            DB::table('thesaurus_labels')->insertOrIgnore([
                'concept_id' => $conceptId,
                'type' => 'prefLabel',
                'literal_form' => $conceptData['label'],
                'language' => 'fr-fr',
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Ajouter le label alternatif si prÃ©sent (idempotent)
            if (isset($conceptData['alt_label'])) {
                DB::table('thesaurus_labels')->insertOrIgnore([
                    'concept_id' => $conceptId,
                    'type' => 'altLabel',
                    'literal_form' => $conceptData['alt_label'],
                    'language' => 'fr-fr',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}

